### PR TITLE
Extract Search as a mixin

### PR DESCRIPTION
**Pull request by Blystad**
With Search extracted as a mixin it becomes easier to create a custom
search field, without having to replicate a lot of functionality.

The current Search implementation has been modified to use the Mixin,
both to preserve backwards compatibility, and to serve as a reference
implementation.

If you're happy with the implementation, I will submit some documentation as well.

### CODE REVIEW

**Comment by bebraw** [comment]
That's a nice idea.

Would it be possible to provide a decorator (`search(elem)(possible options)` or `@search`)? Mixins are problematic with ES6 style classes.

**Comment by Blystad** [comment]
Well, I'm thinking we have four alternatives:
1. [Higher order components](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750). This works quite the same as decorators, but without the ES7/Babel stage=1 requirement.
2. Use only decorators
3. Use only mixins (developers could create decorators from mixins using [react-mixin-decorator](
https://www.npmjs.com/package/react-mixin-decorator))
4. provide both mixin and decorator (using react-mixin-decorator).

I havn't tested react-mixin-decorator, but underneath the hood it works exactly the same as higher-order components.

**Comment by bebraw** [comment]
I would be totally happy with 4. That seems like an option worth exploring. If we can provide something that's easy to consume, that's great.

**Comment by Blystad** [comment]
I tested out `react-mixin-decorator`, and it is pretty much just a fancy way to write a Higher order component. 

It will pass on the declared `propTypes` as well as this.state and this.props (however, merged as props), but passing on other methods seems to be a general nightmare:

I was able to pass on `onQueryChange`, `getOptions`, `onColumnChange` in props, but then eslint would complain that I didn't declare that I needed these props (which is fair, but that results in adding annoying extra proptypes, even if the decorator had these declared).

My final solution was to just extend the already existing `Search` class. It seems React/Babel handles this nicely, and I could just write my component like this:

```javascript
class CustomSearch extends Search {
  render() {
    const searchIcon = (<Icon glyph="search" iconSet="gi" />);

    const dropdownButton = (
      <SplitButton title={searchIcon} bsStyle="primary" pullRight dropdownTitle="Filter">
        <form className="form form-horizontal">
          <Input type="select" onChange={this.onColumnChange.bind(this)} value={this.state.column} label="Filter by">
            {this.getOptions().map((option, i) => <option key={i} value={option.value}>{option.name}</option>)}
          </Input>
        </form>
      </SplitButton>);

    return (<Input type="text" onChange={this.onQueryChange.bind(this)} value={this.state.query} buttonAfter={dropdownButton} />);
  }
}
```

(I actually didn't expect that to work, so I was pleasantly surprised when it did.)

Now, since this was doable without the PR, and since Mixins aren't the recommended solution anymore, I think I will close the PR :)

**Comment by bebraw** [comment]
Great to hear you found a nice solution!

**Comment by eviltoylet** [comment]
:+1:

**Comment by timbur** [comment]
@Blystad at some point I'll create a `v2.0` for `react-mixin-decorator` and I've made a note to consider use cases like yours here.  If you have any other thoughts on it, feel free to add them at https://github.com/timbur/react-mixin-decorator/issues/3.  (I'm also kinda just commenting here so I can quickly come back to this issue later lol.)  :)

**Pull request closed without merging**
