### PR TITLE
Simplest change to support multi-column sorts a la react-datagrid (cy…

### PR DESCRIPTION
**Pull request by JeffSanchez**
…cle through ascending, descending, no sort, independently for each column).

### CODE REVIEW

**Comment by bebraw** [comment]
Can you fix those linting errors and write basic docs (docs/sorting_table.md)?

**Comment by JeffSanchez** [comment]
Thanks, will do tomorrow.

-Jeff

**Comment by JeffSanchez** [comment]
I addressed the lint and doc issues - please let me know if there's something else to update.

**Comment by bebraw** [comment]
Thanks! Just published a new version with the feature in it.

Over longer term this logic might go to a package of its own as it's not tied to Reactabular itself. That will bring down the size of the dist build a notch as well. Now the minified version is around 13.7k which isn't too bad.

**Comment by JeffSanchez** [comment]
Thanks, that makes sense. I appreciate the quick review / approval on the
pull request!

-Jeff

**Pull request merged**
