### PR TITLE
columnIndex-based sorting

### PR DESCRIPTION
**Pull request by skosch**
Hey,

I was still running into trouble with conflicting property values, so I took the liberty to move the sorting stuff over to columnIndices. Essentially my proposal is to use objects for `sortingColumns` instead of arrays, and to get rid of all instances of `indexOf`/`findIndex`. I've adjusted the tests and examples accordingly, although there's a good chance that I missed something here or there.

Could you take a look and consider whether this is a change you're willing to make?

### CODE REVIEW

**Comment by bebraw** [comment]
That seems like a good idea and it cuts down the syntax as well. Could you rebase against the master? I guess something changed along the way. Hopefully it's not too hard to fix.

**Comment by bebraw** [comment]
FYI, I'm going to merge this myself. 👍

**Comment by skosch** [comment]
Ah, sorry about that. I'm only just having breakfast now so I missed your request. Hopefully everything's reasonably clear.

I was also thinking .. there's no reason anymore for `sortable` to be a function returning a function, since it's not even taking any parameters.

**Comment by bebraw** [comment]
@skosch Yeah, good call. I can clean that up.

**Pull request closed without merging**
