### PR TITLE
sort case-insensitively and maintain pre-existing header classes

### PR DESCRIPTION
**Pull request by rdoh**

### CODE REVIEW

**Comment by bebraw** [comment]
Maybe it would make sense to define a separate `sort` function for case-insensitive sorting. The current solution will break backwards compatibility and that might be something we want to avoid.

About that eslint error... Looks like it's due to ESLint 2.3.0. More info: https://github.com/babel/babel-eslint/issues/267 .

**Comment by bebraw** [comment]
I fixed the `master`. It should lint correctly now. Do you want to rebase and force push the changes (feature branch so ok)?

**Comment by bebraw** [comment]
What do you want to do with this?

My current thinking is that we should extract the sorting logic to a little npm package of its own and manage it there. That would be a good chance to sharpen the sort API.

**Comment by rdoh** [comment]
Sorry I haven't had a chance to look at it yet. I think that is a good idea.

**Pull request closed without merging**
