### PR TITLE
Example of filtering data using different filters for each column

### PR DESCRIPTION
**Pull request by szdc**
This adds an example of how to add a filter for each individual column of data, as was requested in #114. Each filter is then applied to the data in succession so the data for each search call is the result of the previous call.

- Wired up the ColumnFilters demo component
- Moved the ColumnFilters component from the FullTable demo component to a new FullTableMultipleFilters component which demonstrates the functionality of this PR
- Added a method _searchMultiple_ that searches across columns, successively filtering the table data

### CODE REVIEW

**Comment by bebraw** [comment]
Great idea.

Can you add docs and tests to cover the new functionality?

**Comment by bebraw** [comment]
Published as `0.13.0`. Thanks again!

Sorry it took a while to merge. I missed your commits.

**Comment by szdc** [comment]
It's all good, I still have to write some tests and update a bit more of the docs which is why I didn't tag you :)
Ive just had a huge amount of university work due over the past two weeks

**Comment by bebraw** [comment]
@szdc It's all good. Another PR is welcome later on. 👍

**Pull request merged**
